- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install logstash configuration files
  template: src=logstash.conf dest=/etc/logstash/conf.d/logstash_{{ item.key }}.conf
  with_dict: logstash.config.file_inputs
  notify: Restart Logstash

- name: Start Logstash
  service: name=logstash state=started
