- name: Install REDIS
  apt: pkg=redis-server state=present update_cache=yes
  tags: deps

- name: Install python-pycurl and python-apt
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - python-pycurl
   - python-apt
  tags: deps

- name: Add Logstash repository
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/{{ logstash.logstash_version }}/debian stable main" state=present

- name: Add Logstash repository  key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install Logstash
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - logstash
   - logstash-contrib
