
elasticsearch:
  dependencies:
    - 'default-jre'
  user: 'elasticsearch'
  group: 'elasticsearch'
  download_url: 'https://download.elasticsearch.org/elasticsearch/elasticsearch'
  version: '1.2.1'
  install_java: true

  # configuration options
  config:

    bind_iface: 'eth1'

    cluster_name: "elasticsearch"
    disable_scripting: true
    limit_cache_size: true

    # By default we let ES allocate half of the available
    # memory on each host.
    heap_size: "{{ ansible_memtotal_mb / 2 }}"

    # mlockall will disable swapping for the ES process
    mlockall: true

    # index settings
    refresh_interval: "5s"
    number_of_shards: 10
    number_of_replicas: 1

# Auto-detect IP address to bind on based on the configured network interface
elasticsearch_bind_ip: "{{ hostvars[inventory_hostname]['ansible_' + elasticsearch.config.bind_iface ].ipv4.address }}"
