---
- name: Install Elasticsearch nodes
  hosts: esnodes
  sudo: yes
  tags: elasticsearch
  roles:
    - esnode

- name: Install Kibana on one of the nodes
  hosts: esnode1
  sudo: yes
  tags: kibana
  roles:
    - kibana

- name: Install Logstash and Redis
  hosts: logstash
  sudo: yes
  tags: logstash
  roles:
    - logstash
