- name: Install REDIS
  apt: pkg=redis-server state=present update_cache=yes
  tags: deps

- name: Install python-pycurl and python-apt
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - python-pycurl
   - python-apt
  tags: deps

- name: Have Redis listen on all interfaces
  lineinfile: dest=/etc/redis/redis.conf regexp="^bind " line="bind 0.0.0.0"
  notify: Restart Redis

- name: Disable Redis background saving
  replace: dest=/etc/redis/redis.conf regexp="^save (.+)$" replace="#save \1"
  notify: Restart Redis

- name: Add Logstash repository
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/{{ logcentral.logstash_version }}/debian stable main" state=present

- name: Add Logstash repository key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install Logstash
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - logstash
   - logstash-contrib

- name: Install Logstash packetbeat configuration
  template: src=logstash_packetbeat.conf dest=/etc/logstash/conf.d/logstash_packetbeat.conf
  notify: Restart Logstash
