
logstash:
    version: 1.4

    config:
        file_inputs:
            syslog:
                enabled: true
                path: "/var/log/syslog"
            nginx_access:
                enabled: true
                path: "/var/log/nginx/access.log"
            nginx_error:
                enabled: true
                path: "/var/log/nginx/error.log"


aggregator_bind_iface: "eth1"
aggregator_bind_ip: "{{ hostvars[groups['aggregator'][0]]['ansible_' + aggregator_bind_iface ].ipv4.address }}"
aggregator_redis_port: 6380

