
logstash:
    version: 1.4

    config:
        file_inputs:
            syslog:
                enabled: true
                path: "/var/log/syslog"
            nginx_access:
                enabled: true
                path: "/var/log/nginx/access.log"
            nginx_error:
                enabled: true
                path: "/var/log/nginx/error.log"


logcentral_bind_iface: "eth1"
logcentral_bind_ip: "{{ hostvars[groups['logcentral'][0]]['ansible_' + logcentral_bind_iface ].ipv4.address }}"
logcentral_redis_port: 6380

