- name: Add Java7 repository
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present update_cache=yes
  when: elasticsearch.install_java
  tags: java

- name: Add Java7 repository key
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886 state=present
  when: elasticsearch.install_java
  tags: java

- name: Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections creates=/usr/lib/jvm/java-7-oracle
  when: elasticsearch.install_java
  tags: java

- name: Install Java7
  apt: pkg=oracle-java7-installer state=present update_cache=yes
  when: elasticsearch.install_java
  tags: java

- name: Add Elasticsearch repository
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch.version }}/debian stable main" state=present

- name: Add Elasticsearch repository key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install Elasticsearch
  apt: pkg=elasticsearch update_cache=yes state=present

- name: ES configuration
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: Restart ES

- name: ES set heap size
  action: >
     lineinfile dest=/etc/init.d/elasticsearch state=present
     regexp="^ES_HEAP_SIZE" insertafter="\#ES_HEAP_SIZE"
     line="ES_HEAP_SIZE={{elasticsearch.config.heap_size|int}}m"
  notify: Restart ES

- name: Start ES
  service: name=elasticsearch state=started

- name: Wait for ES to start
  wait_for: host={{ elasticsearch_bind_ip }} port=9200

- name: Copy ES template file for Packetbeat
  template: src=packetbeat.template.json dest=/tmp/packetbeat.template.json
  register: es_template

- name: Load template
  shell: >
      chdir=/tmp
      curl -XPUT 'http://{{elasticsearch_bind_ip}}:9200/_template/packetbeat' -d @packetbeat.template.json
  when: es_template.changed

- name: Download Packetbeat Dashboards
  get_url: url={{ dashboards.url }}/{{ dashboards.archive }} dest=/tmp/{{ dashboards.archive }}
  register: dashboards_archive

- name: Uncompress Dashboards
  command: chdir=/tmp/ tar xvf {{ dashboards.archive }}
  when: dashboards_archive.changed

- name: Load dashboards
  command: chdir=/tmp/{{ dashboards.dir_name }} ./load.sh {{ elasticsearch_bind_ip }}
  when: dashboards_archive.changed
