- name: Install Elasticsearch dependencies
  apt: pkg={{ item }} state=present update_cache=yes
  with_items: elasticsearch.dependencies
  tags: deps

- name: Configure group
  group: name={{ elasticsearch.group }}

- name: Configure user
  user: name={{ elasticsearch.user }} group={{ elasticsearch.group }} createhome=no

- name: Install python-software-properties
  apt: pkg=python-software-properties state=present update_cache=yes
  tags: deps

# Java tasks

- name: Add Java7 repository
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present update_cache=yes
  when: elasticsearch.install_java
  tags: java

- name: Add Java7 repository key
  apt_key: url=hkp://keyserver.ubuntu.com:80 id=EEA14886 state=present
  when: elasticsearch.install_java
  tags: java

- name: Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections creates=/usr/lib/jvm/java-7-oracle
  when: elasticsearch.install_java
  tags: java

- name: Install Java7
  apt: pkg=oracle-java7-installer state=present update_cache=yes
  when: elasticsearch.install_java
  tags: java

# check if already installed
- shell: if [ -e /usr/share/elasticsearch/lib/elasticsearch-{{ elasticsearch.version }}.jar ]; then echo yes; else echo no; fi;
  register: version_exists
  always_run: True

- name: Download ES deb file
  action: get_url url={{ elasticsearch.download_url }}/elasticsearch-{{ elasticsearch.version }}.deb dest=/tmp/
  when: version_exists.stdout == 'no'

# Uninstall previous version if applicable
- name: Uninstalling previous version if applicable
  shell: dpkg --remove elasticsearch
  when: version_exists.stdout == 'no'
- file: path=/usr/share/elasticsearch state=absent
  when: version_exists.stdout == 'no'

- name: Install ES deb
  shell: dpkg -i --force-confnew /tmp/elasticsearch-{{ elasticsearch.version }}.deb
  when: version_exists.stdout == 'no'

- name: ES configuration
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: Restart ES

- name: ES set heap size
  action: >
     lineinfile dest=/etc/init.d/elasticsearch state=present
     regexp="^ES_HEAP_SIZE" insertafter="\#ES_HEAP_SIZE"
     line="ES_HEAP_SIZE={{elasticsearch.config.heap_size|int}}m"
  notify: Restart ES

- name: Start ES
  service: name=elasticsearch state=started

- name: Copy ES template file for Packetbeat
  template: src=packetbeat.template.json dest=/tmp/packetbeat.template.json
  register: es_template

- name: Load template
  shell: >
      chdir=/tmp
      curl -XPUT 'http://{{elasticsearch.config.bind_ip}}:9200/_template/packetbeat' -d @packetbeat.template.json
  when: es_template.changed
