- name: Install Elasticsearch dependencies
  apt: pkg={{ item }} state=present update_cache=yes
  with_items: elasticsearch.dependencies
  tags: deps

- name: Configure group
  group: name={{ elasticsearch.group }}

- name: Configure user
  user: name={{ elasticsearch.user }} group={{ elasticsearch.group }} createhome=no

# check if already installed
- shell: if [ -e /usr/share/elasticsearch/lib/elasticsearch-{{ elasticsearch.version }}.jar ]; then echo yes; else echo no; fi;
  register: version_exists
  always_run: True

- name: Download ES deb file
  action: get_url url={{ elasticsearch.download_url }}/elasticsearch-{{ elasticsearch.version }}.deb dest=/tmp/
  when: version_exists.stdout == 'no'

# Uninstall previous version if applicable
- name: Uninstalling previous version if applicable
  shell: dpkg --remove elasticsearch
  when: version_exists.stdout == 'no'
- file: path=/usr/share/elasticsearch state=absent
  when: version_exists.stdout == 'no'

- name: Install ES deb
  shell: dpkg -i --force-confnew /tmp/elasticsearch-{{ elasticsearch.version }}.deb
  when: version_exists.stdout == 'no'

- name: ES configuration
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: Restart ES

- name: ES set heap size
  action: >
     lineinfile dest=/etc/init.d/elasticsearch state=present
     regexp="^ES_HEAP_SIZE" insertafter="\#ES_HEAP_SIZE"
     line="ES_HEAP_SIZE={{elasticsearch.config.heap_size}}m"
  notify: Restart ES
