kibana:
    url: https://github.com/packetbeat/kibana/releases/download/v3.1.0-pb
    archive: kibana-3.1.0-packetbeat.tar.gz

    config:
        server_name: "localhost"
        nginx_disable_default: true
